version: '3'

services:
  watchdog:
    image: ghcr.io/singular0/router-watchdog
    environment:
      - ROUTER_HOST=192.168.0.1
      - ROUTER_PASSWORD=password
      - CHECK_HOST=google.com
      - CHECK_ATTEMPTS=3
      - CHECK_INTERVAL=1
      - CHECK_RETRY_INTERVAL=10
      - CHECK_TIMEOUT=10
      - LOG_LEVEL=info
    restart: always
