name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  publish_to_registry:
    name: Push Docker image to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build and publish Docker image
        run: |
          echo $GHCR_PAT | docker login ghcr.io -u $GITHUB_REPOSITORY_OWNER --password-stdin
          docker build . --tag ghcr.io/$GITHUB_REPOSITORY:latest --tag ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME
          docker push ghcr.io/$GITHUB_REPOSITORY:latest
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
